version: "3"
services:
  shiny-app:
    container_name: scilinker
    build:
      context: ../
      dockerfile: deployment/scilinker_dockerfile
    ports:
      - 8002:3838
    network_mode: bridge
    restart: always