version: "3"
services:
  shiny-app:
    container_name: scilinker
    build:
      context: ./deployment/
      dockerfile: scilinker_app_dockerfile
    ports:
      - 3838:3838
      - 27017:27017
    network_mode: bridge
    restart: always
